# Generated by Django 6.1.1 on 2026-09-10 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_name', models.CharField(default='futbol', max_length=50)),
                ('emoji', models.CharField(default='⚽', max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, default='Top-rated sports arena', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Kolhapur', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, default=16.6956, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=74.2317, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=800.0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.IntegerField(default=128)),
                ('badge', models.CharField(blank=True, default='FILLING FAST', max_length=50)),
                ('court_formats', models.CharField(default='5V5, 7V7', max_length=100)),
                ('amenities', models.TextField(default='Floodlights, Changing Room, Turf Shoes Allowed, Free Parking, Mineral Water')),
                ('description', models.TextField(blank=True, default='Modern FIFA standard artificial turf equipped with high-lux LED floodlights, sound system, and dedicated dugouts.')),
                ('image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1529900245534-47fbf82a6036?auto=format&fit=crop&w=1000&q=80', max_length=500)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='grounds/')),
                ('opening_time', models.TimeField(default='06:00:00')),
                ('closing_time', models.TimeField(default='23:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grounds', to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(related_name='grounds', to='grounds.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='grounds.ground')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grounds.sport')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='grounds.timeslot')),
            ],
            options={
                'ordering': ['-booking_date', '-slot__start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['CONFIRMED'])), fields=('ground', 'booking_date', 'slot'), name='unique_ground_date_slot_confirmed')],
            },
        ),
    ]
