# Generated by Django 6.1.1 on 2026-09-27 17:26

from django.utils import timezone
from django.db import migrations, models


def assign_existing_slots_to_today(apps, schema_editor):
    TimeSlot = apps.get_model('grounds', 'TimeSlot')
    TimeSlot.objects.using(schema_editor.connection.alias).filter(
        slot_date__isnull=True,
    ).update(slot_date=timezone.localdate())


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0002_remove_booking_unique_ground_date_slot_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('ground', 'slot_date', 'start_time', 'end_time'), name='unique_ground_date_time_range'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE `grounds_timeslot` DROP INDEX `unique_ground_time_range`',
                    reverse_sql=(
                        'ALTER TABLE `grounds_timeslot` '
                        'ADD CONSTRAINT `unique_ground_time_range` '
                        'UNIQUE (`ground_id`, `start_time`, `end_time`)'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='timeslot',
                    name='unique_ground_time_range',
                ),
            ],
        ),
        migrations.RunPython(assign_existing_slots_to_today, migrations.RunPython.noop),
    ]
